workspace="$(realpath /workspaces/*)"
# This is for a planned future extension
if [ -d "${workspace}/ncbind/Scripts" ]; then
    export PATH="${workspace}/ncbind/Scripts:$PATH"
fi

NCSCRIPTS="${workspace}/Scripts"
if [ -d "$NCSCRIPTS" ]; then
    export PATH="$NCSCRIPTS:$PATH"
    export NCSCRIPTS
else
    unset NCSCRIPTS
fi

case $- in
    *i*) PS1="wincurses\$ "  
        ;;
    *) return;;
esac
