#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/internal/inc
. $SCRIPTS/internal/batch

forbidden_feature() {
    local feature="$1"
    has_feature arg_features "$feature" && \
      _fail "Option -$feature is not allowed when using $SCRIPTNAME, because it is part of the constructed set of builds."
}

get_options() {
    parse_args arg_config arg_features arg_runtime arg_target arg_options arg_parameters -no-defaults "$@"
    [ $? -ne 0 ] && _fail "Error parsing options"

    option_help && {
        cat << EOF
Usage: $0 [options]

  Build configuration (default: debug): Only one of these options can be specified.

    -debug               Build debug version
    -release             Build release version

  Reentrancy options (for improved thread safetyness)

    -reentrant           Build reentrant version

  Target architecture (default: x86_64): Only one of these options can be specified.
                         When not -native, this is the architeture of the Windows OS being targeted.  
    -x86_64              Build for x86_64 (amd64) architecture
    -aarch64             Build for aarch64 (arm64) architecture
    -x86                 Build for x86 (i686) architecture
    -native              Build for native execution in Linux or the host environment

  C-Runtime of the Windows target OS (default: UCRT): Only one of these options can be specified.
                         This is only allowd, when building for Windows.
    -msvcrt              Build with MSVCRT instead of UCRT
    -ucrt                Build with UCRT runtime

  Internal library configuration features:

    -termlib             Build terminfo library only
    -dynamic             Build with shared libraries (default is static)

  Other options:
  
    -clean               Clean build and install directories before building
    -verbose             Enable verbose output
    -log <file>          Log verbose output to the specified file
    -help                Show this help message and exit
EOF
        exit 0
    }

    forbidden_feature wide
    forbidden_feature ascii
    forbidden_feature winconsole
    forbidden_feature conpty
    forbidden_feature interop
    forbidden_feature spfuncs

    return 0
}

in_container && _fail "This script is not meant to be run inside the devcontainer"

get_options $@
[ $? -ne 0 ] && _fail "Error parsing options"


[ -f "$NC_CURRENT_JOB" ] && _fail "A batch build is already running"

addopts=$(common_addopts)

feature_dynamic  && addopts+=" -dynamic"
feature_termlib  && addopts+=" -termlib" 
option_clean     && addopts+=" -clean"
option_verbose   && addopts+=" -verbose"

pushd $PROJROOT >/dev/null
stamp=$(date +"%Y%m%d%H%M%S")
jobid=$(batch <<EOF 2>&1 | sed -n 's/.*[Jj]ob \([0-9][0-9]*\).*/\1/p'
cd $PROJROOT
NCSTAMP=$stamp ./Scripts/internal/ncbatch $addopts
EOF
)
NCJOB=${NC_LOGBASE}/${NC_BATCH_PREFIX}-${stamp}.job
rm -f $NCJOB $NC_CURRENT_JOB
touch $NCJOB
ln -f $NCJOB $NC_CURRENT_JOB
cat >> $NCJOB <<EOF
jobid=$jobid
stamp=$stamp
options="$addopts"
EOF
popd >/dev/null
echo "Queued Wincurses batch job id $jobid, stamp is $stamp"
exit 0
