#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/internal/inc
. $SCRIPTS/internal/batch

err=

_opt_debug=1
_opt_dynamic=0
_opt_libseparate=0
_opt_native=0
_opt_reentrant=0
_opt_ucrt=1
_opt_x86=0
_opt_woa=0

opt_debug() {
    [ $_opt_debug -ne 0 ] && return 0
    return 1
}

opt_dynamic() {
    [ $_opt_dynamic -ne 0 ] && return 0
    return 1
}

opt_reentrant() {
    [ $_opt_reentrant -ne 0 ] && return 0
    return 1
}

opt_libseparate() {
    [ $_opt_libseparate -ne 0 ] && return 0
    return 1
}

opt_native() {
    [ $_opt_native -ne 0 ] && return 0
    return 1
}

opt_ucrt() {
    [ $_opt_ucrt -ne 0 ] && return 0
    return 1
}

opt_x86() {
    [ $_opt_x86 -ne 0 ] && return 0
    return 1
}

opt_woa() {
    [ $_opt_woa -ne 0 ] && return 0
    return 1
}

opt_clean() {
    [ $_opt_clean -ne 0 ] && return 0
    return 1
}

get_options() {
    local err=
    while [[ $# -gt 0 ]]
    do
	    case "$1" in
            -N|--native)
                _opt_native=1
                ;;
            -m|--msvcrt)
                _opt_ucrt=0
                ;;
            -w|--woa)
                _opt_woa=1
                ;;
            -x|--x86)
                _opt_x86=1
                ;;
            -t|--reentrant)
                _opt_reentrant=1
                ;;
            -n|--nodebug)
                _opt_debug=0
                ;;
            -v|--verbose)
                _opt_verbose=1
                ;;
            -d|--dynamic)
                _opt_dynamic=1
                ;;
            -l|--libseparate)
                _opt_libseparate=1
                ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -N, --native          Build for native execution in Linux (no cross-compilation)"
                echo "  -m, --msvcrt          Build with MSVCRT instead of UCRT (Windows only)"
                echo "  -w, --woa             Build for Windows on ARM (WoA)"
                echo "  -x, --x86             Build for x86 (32-bit)"
                echo "  -t, --reentrant       Build also all combinations possible with --reentrant, results in 16 builds."
                echo "  -d, --dynamic         Build with shared libraries (default is static)"
                echo "  -l, --libseparate     Build separate tinfo library (default is combined with ncurses)"
                echo "  -n, --nodebug         Build without debug symbols and features"
                echo "  -v, --verbose         Enable verbose output"
                echo "  -h, --help            Show this help message and exit"
                exit 0
                ;;
	        --)
		        shift
		        break
		        ;;
            -*)
                _fail "Unknown option: $1"
                ;;    
	        *)
		        err="$err $1"
		        break
		        ;;
	    esac
        shift
    done
    [ -n "$err" ] && _fail "Invalid commandline argument(s): $err"
    return 0
}

in_container && _fail "This script is not meant to be run inside the devcontainer"
[ -f "$NC_CURRENT_JOB" ] && _fail "A batch build is already running"

get_options $@
[ $? -ne 0 ] && _fail "Invalid options: $err"

addopts=
! opt_debug     && addopts+=" --nodebug"
! opt_ucrt      && addopts+=" --msvcrt"
opt_x86         && addopts+=" --x86"
opt_woa         && addopts+=" --woa"
opt_dynamic     && addopts+=" --dynamic"
opt_libseparate && addopts+=" --libseparate" 
opt_verbose     && addopts+=" --verbose"
opt_native      && addopts+=" --native"

pushd $PROJROOT >/dev/null
stamp=$(date +"%Y%m%d%H%M%S")
jobid=$(batch <<EOF 2>&1 | sed -n 's/.*[Jj]ob \([0-9][0-9]*\).*/\1/p'
cd $PROJROOT
NCSTAMP=$stamp ./Scripts/internal/ncbatch $addopts
EOF
)
NCJOB=${NC_LOGBASE}/${NC_BATCH_PREFIX}-${stamp}.job
rm -f $NCJOB $NC_CURRENT_JOB
touch $NCJOB
ln -f $NCJOB $NC_CURRENT_JOB
cat >> $NCJOB <<EOF
jobid=$jobid
stamp=$stamp
EOF
popd >/dev/null
echo "Queued Wincurses batch job id $jobid, stamp is $stamp"
exit 0
