#!/usr/bin/env bash
# Please see License.md in the root of the project for license information.
# Copyright (c) 2026 Juergen Pfeifer.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/internal/inc
. $SCRIPTS/internal/bulk

err=
_jobid=
_stamp=
_mainopt=0

_opt_delete=0
_opt_purge=0
_opt_list=0
_opt_show=0
_opt_out=0
_opt_err=0

opt_delete() {
    [ $_opt_delete -ne 0 ] && return 0
    return 1
}

opt_purge() {
    [ $_opt_purge -ne 0 ] && return 0
    return 1
}

opt_list() {
    [ $_opt_list -ne 0 ] && return 0
    return 1
}

opt_show() {
    [ $_opt_show -ne 0 ] && return 0
    return 1
}

opt_out() {
    [ $_opt_out -ne 0 ] && return 0
    return 1
}

opt_err() {
    [ $_opt_err -ne 0 ] && return 0
    return 1
}

_guess_jobid() {
    local jobid=$(last_jobid)
    local f
    [ $jobid -ne 0 ] || _fail "No previous job found to guess job ID from"
    f=$(jobfile_for_jobid $jobid)
    [ -f "$f" ] || _fail "No job file found for last job ID $jobid"
    echo "$jobid"
}

get_options() {
    local err=
    while [[ $# -gt 0 ]]
    do
	    case "$1" in
            -l|-list)
                _opt_list=1
                _mainopt=$(expr $_mainopt + 1)
                ;;
            -s|-show)
                _opt_show=1
                _mainopt=$(expr $_mainopt + 1)
                shift
                if [ $# -gt 0 ]; then
                    _jobid="$1"
                else
                    _jobid=$(_guess_jobid)
                fi
                [ -n "$_jobid" ] || _fail "Invalid job ID for --show option"
                ;;
            -d|-delete)
                _opt_delete=1
                _mainopt=$(expr $_mainopt + 1)
                shift
                if [ $# -gt 0 ]; then
                    _jobid="$1"
                else
                    _fail "-delete requires jobid"
                fi
                ;;
            -p|-purge)
                _opt_purge=1
                _mainopt=$(expr $_mainopt + 1)
                ;;
            -o|-out)
                [ $_opt_show -ne 0 ] && _fail "--out option must be used before -show"
                _opt_out=1
                ;;
            -e|-err)
                [ $_opt_show -ne 0 ] && _fail "--err option must be used before -show"
                _opt_err=1
                ;;
            -v|-verbose)
                _nc_verbose=1
                ;;
            -h|-help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -l, -list    List all job entries (this is the default if no other options are specified)."
                echo "  -s, -show    Show details of a specific job entry."
                echo "  -d, -delete  Delete a specific job entry."
                echo "  -p, -purge   Purge all job entries."
                echo "  -o, -out     Show the standard output of a specific job entry."
                echo "  -e, -err     Show the standard error of a specific job entry."
                exit 0
                ;;
	        --)
		        shift
		        break
		        ;;
            -*)
                _fail "Unknown option: $1"
                ;;    
	        *)
		        err="$err $1"
		        break
		        ;;
	    esac
        shift
    done
    [ -n "$err" ] && _fail "Invalid commandline argument(s): $err"
    return 0
}


get_options $@
[ $? -ne 0 ] && _fail "Invalid options: $err"
[ $_mainopt -gt 1 ] && _fail "Only one of --delete, --list, --show or --purge options can be specified at the same time"

if opt_out || opt_err; then
    if [ -z "$_jobid" ]; then
        _fail "Job ID must be specified with -out or -err option"
    fi
    if ! opt_show; then
        _fail "--show option must be specified with -out or -err option"
    fi
    opt_out && opt_err && _fail "Cannot specify both -out and -err options at the same time"
fi

_list() {
    local jobid
    local stamp
    local options
    local runfile
    local mark=
    local type=

    for job in *.job
    do
        mark=" "
        [ -f "$job" ] || continue
        runfile="${job%.job}.run"
        [ -f "$runfile" ] && mark="*"
        source $job
        echo "${mark}JobID: $jobid, Timestamp: $stamp, Type: $type, Options: $options"
    done | sort -k 4 -u -r
}


_find_job() {
    local job="$1"
    local jobfile=$(jobfile_for_jobid $job)
    local res=
    local jobid
    local stamp
    local type  
    local options
    
    [ -f "$jobfile" ] || _fail "No job found with ID $job"
    source "$jobfile"
    [ "$jobid" == "$job" ] && res="$jobfile"    
    echo "$res"
}

_show() {
    local jobfile="$(_find_job $_jobid)"
    local jobid
    local stamp
    local type
    local options
    local name=
    local ext="log"
    local pager=$(type -p less)
    [ -n "$pager" ] || pager=$(type -p more)
    [ -z "$pager" ] && pager=cat
    [ -n "$jobfile" ] || _fail "No job found with ID $_jobid"
    source "$jobfile"
    name=${NC_BULK_PREFIX}-${jobid}
    opt_out && ext="out"
    opt_err && ext="err"
    if [ -f "${name}.${ext}.xz" ]; then
        xzcat "${name}.${ext}.xz" | $pager
    else
        if [ -f "${name}.${ext}" ]; then
            $pager "${name}.${ext}"
        else
            _fail "No ${ext} file found for job ID $_jobid - it can take a few moments until these files are available after job creation."
        fi
    fi
}

_delete() {
    _trace "Deleting job with ID $_jobid"
    delete_job "$_jobid" || _fail "Cannot delete job with ID $_jobid. Maybe it is still running."
}

pushd ${NC_LOG_ROOT} >/dev/null
[ $_mainopt -eq 0 ] && _list
opt_list && _list
opt_show && _show
opt_delete && _delete
opt_purge && purge_jobs
popd >/dev/null
exit 0
