#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/_inc

err=

_opt_debug=1
_opt_dynamic=0
_opt_libseparate=0
_opt_native=0
_opt_clean=0
_opt_reentrant=0
_opt_ucrt=1
_opt_x86=0
_opt_woa=0


opt_debug() {
    [ $_opt_debug -ne 0 ] && return 0
    return 1
}

opt_dynamic() {
    [ $_opt_dynamic -ne 0 ] && return 0
    return 1
}

opt_reentrant() {
    [ $_opt_reentrant -ne 0 ] && return 0
    return 1
}

opt_libseparate() {
    [ $_opt_libseparate -ne 0 ] && return 0
    return 1
}

opt_native() {
    [ $_opt_native -ne 0 ] && return 0
    return 1
}

opt_ucrt() {
    [ $_opt_ucrt -ne 0 ] && return 0
    return 1
}

opt_x86() {
    [ $_opt_x86 -ne 0 ] && return 0
    return 1
}

opt_woa() {
    [ $_opt_woa -ne 0 ] && return 0
    return 1
}

opt_clean() {
    [ $_opt_clean -ne 0 ] && return 0
    return 1
}

doit() {
    ${SCRIPTS}/ncbuild $@
    [ $? -ne 0 ] && _fail "Build failed with options: $@"
}

doall() {
    local optargs="$@"
    local msvcrt=
    local nocon=0
    local expected=0
    local libs="ncurses panel menu form"
    local lib
    local cnt=0

    opt_libseparate && libs+=" tinfo"

    if opt_native; then
        if opt_reentrant; then
            OPTARGS=$optargs powerCall doit --ascii --interop --spfuncs --reentrant
            expected=16
        else
            OPTARGS=$optargs powerCall doit --ascii --interop --spfuncs
            expected=8
        fi
    else
        opt_ucrt && msvcrt="--msvcrt"
        opt_woa && nocon=1
        if opt_reentrant; then
            OPTARGS=$optargs powerCall doit --ascii --interop --spfuncs --reentrant
            [ $nocon -eq 0 ] && OPTARGS="$optargs --noconpty --winconsole $msvcrt" powerCall doit --ascii --interop --spfuncs --reentrant
            [ $nocon -eq 0 ] && OPTARGS="$optargs --winconsole $msvcrt" powerCall doit --ascii --interop --spfuncs --reentrant
            expected=16
            [ $nocon -eq 0 ] && expected=48
        else
            OPTARGS=$optargs powerCall doit --ascii --interop --spfuncs
            [ $nocon -eq 0 ] && OPTARGS="$optargs --noconpty --winconsole $msvcrt" powerCall doit --ascii --interop --spfuncs
            [ $nocon -eq 0 ] && OPTARGS="$optargs --winconsole $msvcrt" powerCall doit --ascii --interop --spfuncs
            expected=8
            [ $nocon -eq 0 ] && expected=24
        fi
    fi
    for lib in $libs; do
        cnt=$(find ${PROJROOT}/${_relative_buildroot} -type f -name "lib${lib}*.a" | grep -v _g\\.a$ | grep -v \\.dll\\.a$ | wc -l)
        if [ $cnt -ne $expected ]; then
            _log "Expected $expected builds for library ${lib} but found $cnt. Please check the build output for errors."
        else
            _log "Found expected $cnt builds for library ${lib}."
        fi
    done          
}

get_options() {
    local err=
    while [[ $# -gt 0 ]]
    do
	    case "$1" in
            -c|--clean)
                _opt_clean=1
                ;;
            -N|--native)
                _opt_native=1
                ;;
            -m|--msvcrt)
                _opt_ucrt=0
                ;;
            -w|--woa)
                _opt_woa=1
                ;;
            -x|--x86)
                _opt_x86=1
                ;;
            -t|--reentrant)
                _opt_reentrant=1
                ;;
            -n|--nodebug)
                _opt_debug=0
                ;;
            -v|--verbose)
                _opt_verbose=1
                ;;
            -d|--dynamic)
                _opt_dynamic=1
                ;;
            -l|--libseparate)
                _opt_libseparate=1
                ;;
	        --log)
		        shift
                _logfile="$1"
		        ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -c, --clean           Clean build and install directories before building"
                echo "  -N, --native          Build for native execution in Linux (no cross-compilation)"
                echo "  -m, --msvcrt          Build with MSVCRT instead of UCRT (Windows only)"
                echo "  -w, --woa             Build for Windows on ARM (WoA)"
                echo "  -x, --x86             Build for x86 (32-bit)"
                echo "  -t, --reentrant       Build also all combinations possible with --reentrant, results in 16 builds."
                echo "  -d, --dynamic         Build with shared libraries (default is static)"
                echo "  -l, --libseparate     Build separate tinfo library (default is combined with ncurses)"
                echo "  -n, --nodebug         Build without debug symbols and features"
                echo "  -v, --verbose         Enable verbose output"
                echo " --log <file>           Log verbose output to the specified file"
                echo "  -h, --help            Show this help message and exit"
                exit 0
                ;;
	        --)
		        shift
		        break
		        ;;
            -*)
                _fail "Unknown option: $1"
                ;;    
	        *)
		        err="$err $1"
		        break
		        ;;
	    esac
        shift
    done
    [ -n "$err" ] && _fail "Invalid commandline argument(s): $err"
    return 0
}

get_options $@
[ $? -ne 0 ] && _fail "Invalid options: $err"

if ! opt_native; then
    in_container || _fail "Not running in devcontainer." 
fi

avoid_hostrun

addopts=
! opt_debug     && addopts+=" --nodebug"
! opt_ucrt      && addopts+=" --msvcrt"
opt_x86         && addopts+=" --x86"
opt_woa         && addopts+=" --woa"
opt_dynamic     && addopts+=" --dynamic"
opt_libseparate && addopts+=" --libseparate" 
opt_clean       && addopts+=" --clean"
opt_verbose     && addopts+=" --verbose"
opt_native      && addopts+=" --native"

doall $addopts

exit 0
