#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS//internal/inc


doit() {
    _log "ncbuild -ascii $@"
    ${SCRIPTS}/ncbuild -ascii $@
    [ $? -ne 0 ] && _fail "Build failed with options: -ascii $@"
    _log "ncbuild -wide $@"
    ${SCRIPTS}/ncbuild -wide $@
    [ $? -ne 0 ] && _fail "Build failed with options: -wide $@"
}

doall() {
    local optargs="$@"
    local rtoldcon=
    local msvcrt=
    local nocon=0
    local expected=0
    local libs="ncurses panel menu form"
    local lib
    local cnt=0
    local prf=$(build_prefix)

    feature_termlib && libs+=" tinfo"

    if target_native; then
        if feature_reentrant; then
            OPTARGS=$optargs powerCall doit -ascii -interop -spfuncs -reentrant
            expected=16
        else
            OPTARGS=$optargs powerCall doit -ascii -interop -spfuncs
            expected=8
        fi
    else
        if runtime_ucrt; then
            rtoldcon="-msvcrt"
            while [ $# -gt 0 ]; do
                case "$1" in
                    -ucrt)
                        ;;
                    *)
                        rtoldcon+=" $1"
                        ;;
                esac
                shift
            done
        fi 
        target_aarch64 && nocon=1
        if feature_reentrant; then
            OPTARGS="$optargs -conpty" powerCall doit -interop -spfuncs -reentrant
            [ $nocon -eq 0 ] && OPTARGS="$rtoldcon -conpty -winconsole" powerCall doit -interop -spfuncs -reentrant
            [ $nocon -eq 0 ] && OPTARGS="$rtoldcon -winconsole" powerCall doit -interop -spfuncs -reentrant
            expected=16
            [ $nocon -eq 0 ] && expected=48
        else
            OPTARGS="$optargs -conpty" powerCall doit -interop -spfuncs
            [ $nocon -eq 0 ] && OPTARGS="$rtoldcon -conpty -winconsole" powerCall doit -interop -spfuncs
            [ $nocon -eq 0 ] && OPTARGS="$rtoldcon -winconsole" powerCall doit -interop -spfuncs
            expected=8
            [ $nocon -eq 0 ] && expected=24
        fi
    fi
    for lib in $libs; do
        cnt=$(find ${PROJROOT}/${_relative_buildroot} -type f -name "lib${lib}*.a" | grep $prf | grep -v _g\\.a$ | grep -v \\.dll\\.a$ | wc -l)
        if [ $cnt -ne $expected ]; then
            _log "Expected $expected builds for library ${lib} but found $cnt. Please check the build output for errors."
        else
            _log "Found expected $cnt builds for library ${lib}."
        fi
    done          
}

forbidden_feature() {
    local feature="$1"
    has_feature arg_features "$feature" && \
      _fail "Option -$feature is not allowed when using $SCRIPTNAME, because it is part of the constructed set of builds."
}

get_options() {
    local l_runtime=0
    parse_args arg_config arg_features arg_runtime arg_target arg_options arg_parameters -no-defaults "$@"
    [ $? -ne 0 ] && _fail "Error parsing options"

    option_help && {
        cat << EOF
Usage: $SCRIPTNAME [options]

  Build configuration (default: debug): Only one of these options can be specified.

    -debug               Build debug version (This is the default)
    -release             Build release version

  Reentrancy options (for improved thread safetyness)

    -reentrant           Build reentrant version

  Target architecture (default: x86_64): Only one of these options can be specified.
                         When not -native, this is the architeture of the Windows OS being targeted.

    -x86_64              Build for x86_64 (amd64) architecture
    -aarch64             Build for aarch64 (arm64) architecture
    -x86                 Build for x86 (i686) architecture
    -native              Build for native execution in Linux or the host environment

  C-Runtime of the Windows target OS (default: UCRT): Only one of these options can be specified.
                         This is only allowd, when building for Windows.

    -ucrt                Build with UCRT runtime
    -msvcrt              Build with MSVCRT instead of UCRT

  Internal library configuration features:

    -termlib             Build terminfo library only
    -dynamic             Build with shared libraries (default is static)

  Other options:
  
    -clean               Clean build and install directories before building
    -verbose             Enable verbose output
    -log <file>          Log verbose output to the specified file
    -help                Show this help message and exit
EOF
        exit 0
    }

    l_runtime="${#runtime[*]}"
    [ $l_runtime -gt 0 ] && fail "Runtime selection will be handled by $SCRIPTNAME, please do not specify runtime options when using $SCRIPTNAME."
    
    forbidden_feature wide
    forbidden_feature ascii
    forbidden_feature winconsole
    forbidden_feature conpty
    forbidden_feature interop
    forbidden_feature spfuncs

    return 0
}

get_options $@
[ $? -ne 0 ] && _fail "Error parsing options"

if ! target_native; then
    in_container || _fail "Not running in devcontainer." 
fi

avoid_hostrun

addopts=$(common_addopts)

feature_dynamic  && addopts+=" -dynamic"
feature_termlib  && addopts+=" -termlib" 
option_clean     && addopts+=" -clean"
option_verbose   && addopts+=" -verbose"

doall $addopts

exit 0
