#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/_inc

get_options() {
    local err=
    while [[ $# -gt 0 ]]
    do
	    case "$1" in
	        -a|--ascii)
	            ;;
            -t|--reentrant)
	            ;;
            -T|--termdriver)
                ;;    
            -i|--interop)
                ;;
            -s|--spfuncs)
                ;;
            -N|--native)
                _opt_native=1
                ;;
            -l|--libseparate)
                ;;
            -m|--msvcrt)
	            ;;
            -n|--nodebug)
                ;;
            -c|--clean)
                ;;
            -w|--woa)
                ;;
            -x|--x86)
                ;;
            -v|--verbose)
                _opt_verbose=1
                ;;
            -d|--dynamic)
                ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -a, --ascii           Build ASCII version (disable wide character support)"
                echo "  -t, --reentrant       Build reentrant version"
                echo "  -T, --termdriver      Build with term-driver support (intended for legacy Windows support)"
                echo "  -i, --interop         Build with interop features enabled"
                echo "  -s, --spfuncs         Build with sp-funcs support."
                echo "  -N, --native          Build for native execution in Linux or the host environment"
                echo "  -m, --msvcrt          Build with MSVCRT instead of UCRT"
                echo "  -w, --woa             Build for Windows on ARM (WOA) with UCRT"
                echo "  -x, --x86             Build for x86 (i686) with MSVCRT"
                echo "  -l, --libseparate     Build terminfo library separately from ncurses"
                echo "  -d, --dynamic         Build with shared libraries (default is static)"
                echo "  -n, --nodebug         Build without debug symbols and features"
                echo "  -c, --clean           Clean build and install directories before building"
                echo "  -v, --verbose         Enable verbose output"
                echo "  -h, --help            Show this help message and exit"
                shift
                exit 0
                ;;
	        --)
		        shift
		        break
		        ;;
            -*)
                _fail "Unknown option: $1"
                ;;
	        *)
		        err="$err $1"
		        ;;
	    esac
        shift
    done
    [ -n "$err" ] && _fail "Invalid commandline argument(s): $err"
    return 0
}

get_options "$@"
[ $? -ne 0 ]  && _fail "Error parsing options"

if ! opt_native; then
    in_container || _fail "Not running in devcontainer." 
fi

# avoid_hostrun

if is_default_build "$@"; then
    _trace "Running with default settings (Windows cross build with widec support, UCRT target, debug build)"
fi

common_consistency_checks "$@"

_trace "Build prefix: $(build_prefix "$@")"
_trace "Configuration prefix: $(get_config_prefix "$@")"
_trace "Library suffix: $(get_suffix "$@")"
_trace "Relative build directory: $(relative_builddir "$@")"
_trace "Relative install base: $(relative_installbase "$@")"
_trace "Relative install directory: $(relative_installdir "$@")"

build_bht=$(uname -m)-linux-gnu
host_bht=
if ! opt_native; then
    host_bht=$(get_host_bht "$@")
    env_file=$PROJROOT/.devcontainer/crossenvs/${host_bht}.env
    if [ -f "$env_file" ]; then
        _trace "Sourcing cross build environment from: ${env_file}"
        source "$env_file"
    else
        _fail "Cross build environment file not found: ${env_file}"
    fi  
    _trace "Host target compiler: ${host_bht}, Build environment: ${build_bht}"
else
    if is_native_darwin; then
	    _trace "On Darwin we use the system compiler toolchain for native builds"
	    export CC=cc
	    export CXX=c++
	    export CPP=cpp
	    export LD=ld
	    export NM=nm
	    export AR=ar
	    export RANLIB=ranlib
	    export AS=as
	    export OBJDUMP=objdump
	    export STRIP=strip
    fi
fi

# When we are running in WSL2, we need to generate a .gdbinit file that contains 
# the correct paths to the repository and the WSL distribution name. This file 
# will be used by GDB to set up the environment for debugging Wincurses in Windows.
# This is necessary because we compile inside the container and gdb cannot generate
# source file references that are resolvable under Windows later on.
gen_gdbinit() {
    local d
    local p 
    pushd "$PROJROOT" >/dev/null
    for p in $(for d in ncurses panel menu form test; do find ncurses/$d -type d ; done | grep -v package)
    do
        echo "directory //wsl.localhost/${WSL_DISTRO_NAME}${ORIGINAL_REPO_PATH}/${p}"
    done
    echo "directory //wsl.localhost/${WSL_DISTRO_NAME}${ORIGINAL_REPO_PATH}/build/$(relative_builddir "$@")/include"
    popd >/dev/null
}

# When we are running in Parallels Desktop, we need to generate a .gdbinit file that 
# contains the correct paths to the repository in the MacOS filesystem.  
gen_gdbinit_prl() {
    local d
    local p
    local win_p 
    source "${PROJROOT}/.prlpath" 
    pushd "$PROJROOT" >/dev/null
    win_p="${WIN_REPO_PATH//\\/\/}"
    for p in $(for d in ncurses panel menu form test; do find ncurses/$d -type d ; done | grep -v package)
    do
        echo "directory ${win_p}/$p"
    done
    p="build/$(relative_builddir "$@")/include"
    echo "directory ${win_p}/$p"
    popd >/dev/null
}


do_config() {
    source "$SCRIPTS/_function_prolog"

    local srcdir=$PROJROOT/ncurses
    local blddir=${PROJROOT}/${_relative_buildroot}/$(relative_builddir "${_args[@]}")
    local cfg=$srcdir/configure
    local dynopts="--with-shared"
    local opts=
    local cflags= 
    local ldflags=
    local prefix=$(get_config_prefix "${_args[@]}")

    [ -x "$cfg" ] || _fail "Configure script not found or not executable: $cfg"

    if is_default_build "${_args[@]}"; then
        _interop=1
        _spfuncs=0
        _termdriver=0
    fi

    if [ $_native -eq 0 ]; then
        opts+=" --build=${build_bht} \
            --host=${host_bht} 
            --with-strip-program=${STRIP} \
            --with-build-cc=${build_bht}-gcc \
            --with-build-cpp=${build_bht}-cpp"    
    fi

    if [ $_dynamic -eq 0 ]; then
        dynopts="--without-shared"
    fi
    if [ $_termdriver -ne 0 ]; then
        opts+=" --enable-term-driver"
    else
        opts+=" --disable-term-driver"
    fi
    if [ $_interop -ne 0 ]; then
        opts+=" --enable-interop"
    else
        opts+=" --disable-interop"
    fi
    if [ $_spfuncs -ne 0 ]; then
        opts+=" --enable-sp-funcs"
    else
        opts+=" --disable-sp-funcs"
    fi
    if [ $_reentrant -ne 0 ]; then
        opts+=" --enable-reentrant"
    else
        opts+=" --disable-reentrant"
    fi
    if [ $_widec -ne 0 ]; then
        opts+=" --enable-widec"
    else
        opts+=" --disable-widec"
    fi

    if [ $_native -eq 0 ]; then
        if [ $_termdriver -ne 0 ]; then
            cflags="$cflags -DUSE_WIN32CON_DRIVER"
            opts+=" --disable-conpty"
        else
            opts+=" --enable-conpty"
        fi
        opts+=" \
            --enable-named-pipes \
            --disable-home-terminfo \
            --disable-symlinks \
            --with-fallbacks=ms-terminal,xterm-256color,xterm,ansi,vt100 \
            --without-manpages"
            # we enforce PCRE2 usage on Windows build in this devcontainer.
            cflags="$cflags -DJPF=0 -I${PCRE2_ROOT}/include -DPCRE2_STATIC -DHAVE_REGEX_H=1 -DHAVE_REGEX_H_FUNCS=1"
            ldflags="$ldflags -L${PCRE2_ROOT}/lib"
    else
        opts+=" \ 
            --enable-home-terminfo \
            --enable-symlinks \
            --with-fallbacks=linux,screen-256color,screen,xterm-256color,xterm,vt100 \
            --without-manpages"
    fi
    
    rm -rf "$blddir"
    mkdir -p "$blddir"
    _trace "Recreated build directory: ${blddir}"

    opts="$opts --with-normal \
        --with-pkg-config \
        --without-cxx --without-ada \
        $dynopts"
    
    if [ $_libseparate -ne 0 ]; then
        opts="$opts --with-termlib"
    else
        opts="$opts --without-termlib"
    fi

    if [ $_debug -ne 0 ]; then
        cflags="$cflags -g"
        opts="$opts \
            --without-manpages \
            --with-debug \
            --with-progs \
            --with-tests \
            --with-develop \
            --with-trace \
            --enable-asserts \
            --enable-database \
            --enable-db-install \
            --enable-warnings \
            --enable-assertions" 
    else
        opts="$opts \
            --without-debug \
            --without-progs \
            --without-tests \
            --without-develop \
            --without-trace \
            --disable-assertions \
            --enable-db-install"
    fi

    opts="$opts --disable-leaks \
        --disable-macros \
        --disable-getcap \
        --disable-hard-tabs \
        --disable-overwrite \
        --disable-termcap \
        --enable-opaque-curses \
        --enable-opaque-panel \
        --enable-opaque-menu \
        --enable-opaque-form \
        --enable-pc-files"

    if [ $_dynamic -ne 0 ]; then
        if [ $_native -ne 0 ]; then
	        if ! is_native_darwin; then
		        ldflags="$ldflags -static-libgcc -Wl,-Bdynamic"
	        fi
        else
            ldflags="$ldflags -static-libgcc -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic"
        fi
    fi

    _trace "Configuration options: ${opts}"
    if [ "$SCRIPTNAME" = "ncbuildinfo" ]; then
        echo "configure_options=\"${opts}\""
        echo "cflags=\"${cflags}\""
        echo "ldflags=\"${ldflags}\""
        return 0
    fi

    pushd "$blddir" >/dev/null
    if [ $_native -eq 0 ]; then
        # Add PCRE2 libraries to LIBS so they appear at the end of the link line
        CFLAGS="${cflags}" LDFLAGS="${ldflags}" LIBS="-lpcre2-posix -lpcre2-8" \
        ${cfg} ${opts} --prefix="/${prefix}" \
            --datadir="/${prefix}/share" \
            --srcdir="${srcdir}"
    else
        CFLAGS="${cflags}" LDFLAGS="${ldflags}" \
        ${cfg} ${opts} --prefix="/${prefix}" \
            --datadir="/${prefix}/share" \
            --srcdir="${srcdir}"
    fi
    popd >/dev/null
    if [ $_dynamic -eq 0 ]; then
        echo "S" > "$blddir/.static"
        rm -f "$blddir/.dynamic"
    else
        echo "D" > "$blddir/.dynamic"
        rm -f "$blddir/.static"
    fi
}

do_build() {
    source "$SCRIPTS/_function_prolog"
    local srcdir=$PROJROOT/ncurses
    local blddir=${PROJROOT}/${_relative_buildroot}/$(relative_builddir "${_args[@]}")

    if [ $_clean -ne 0 ]; then
        _trace "Cleaning build directory: ${blddir}"
        rm -rf "${blddir}"
    fi
    _trace "Build directory: ${blddir}, creating..."
    mkdir -p "${blddir}"

    if [ ! -f "$blddir/Makefile" ]; then
        do_config "${_args[@]}"
    else
        if [ $_dynamic -eq 0 ] && [ -f "$blddir/.dynamic" ]; then
            _trace "Configuration mismatch: previously configured for dynamic, now static. Reconfiguring..."
            do_config "${_args[@]}"
        elif [ $_dynamic -ne 0 ] && [ -f "$blddir/.static" ]; then
            _trace "Configuration mismatch: previously configured for static, now dynamic. Reconfiguring..."
            do_config "${_args[@]}"
        else
            _trace "Existing configuration matches current options. Skipping configuration step."
        fi
    fi

    make -j$(nproc) -C "$blddir"
    [ $? -ne 0 ] && _fail "Build failed"

    if [ $_debug -ne 0 ] && [ $_woa -eq 0 ] ; then
        if maybe_parallels_desktop; then
            gen_gdbinit_prl "${_args[@]}" > ${blddir}/test/.gdbinit
            _trace "Generated .gdbinit for Parallels Desktop: ${blddir}/test/.gdbinit"
        fi
        if in_wsl2; then
            gen_gdbinit "${_args[@]}" > ${blddir}/test/.gdbinit
            _trace "Generated .gdbinit for WSL2: ${blddir}/test/.gdbinit"
        fi
    fi
    return 0
}

do_install() {
    source "$SCRIPTS/_function_prolog"
    local srcdir=$PROJROOT/ncurses
    local blddir=${PROJROOT}/${_relative_buildroot}/$(relative_builddir "${_args[@]}")
    local instdir=${PROJROOT}/${_relative_instroot}/$(relative_installbase "${_args[@]}")

    if [ $_clean -ne 0 ]; then
        _trace "Cleaning install directory: ${instdir}"
        rm -rf "${instdir}"
    fi
    _trace "Install directory: ${instdir}, creating..."
    mkdir -p "${instdir}"

    _trace "Installing to: ${instdir}"
    make -j$(nproc) -C "$blddir" install DESTDIR="$instdir"
    [ $? -ne 0 ] && _fail "Install failed"
    rm -rf "${instdir}/opt"
}

if [ "$SCRIPTNAME" = "ncbuildinfo" ]; then
cat <<EOF
prefix="$(get_config_prefix "$@")"
library_suffix="$(get_suffix "$@")"
extra_suffix="$(get_extra_suffix "$@")"
relative_build_directory="$(relative_builddir "$@")"
relative_install_base="$(relative_installbase "$@")"
relative_install_directory="$(relative_installdir "$@")" 
target_arch="$(get_target_arch "$@")"
EOF
do_config "$@"
    exit 0
fi

do_build "$@"
[ $? -ne 0 ] && _fail "Build failed"

do_install "$@"
[ $? -ne 0 ] && _fail "Install failed"

exit 0
