#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPT=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPT/_inc

abiversion=6
#
# Subdirectory prefixes for MSYS2 builds
MINGW64_PREFIX=mingw64        # x86_64 gcc msvcrt
MINGW32_PREFIX=mingw32        # i686 gcc msvcrt
UCRT64_PREFIX=ucrt64          # x86_64 gcc ucrt
CLANG64_PREFIX=clang64        # x86_64 clang ucrt
CLANG64ARM_PREFIX=clangarm64  # aarch64 clang ucrt
NATIVE_PREFIX=usr             # Native Linux build
#

err=

_cfgopts=0 # Count the number of options that affect the configuration
_nondefault_opts=0 # Count the number of options that differ from the default configuration

_opt_widec=1
_opt_reentrant=0
_opt_ucrt=1
_opt_debug=1
_opt_clean=0
_opt_woa=0
_opt_x86=0
_opt_dynamic=0
_opt_libseparate=0
_opt_native=0
_opt_interop=0
_opt_spfuncs=0

opt_widec() {
    [ $_opt_widec -ne 0 ] && return 0
    return 1
}

opt_reentrant() {
    [ $_opt_reentrant -ne 0 ] && return 0
    return 1
}

opt_ucrt() {
    [ $_opt_ucrt -ne 0 ] && return 0
    return 1
}

opt_debug() {
    [ $_opt_debug -ne 0 ] && return 0
    return 1
}

opt_clean() {
    [ $_opt_clean -ne 0 ] && return 0
    return 1
}

opt_woa() {
    [ $_opt_woa -ne 0 ] && return 0
    return 1
}

opt_x86() {
    [ $_opt_x86 -ne 0 ] && return 0
    return 1
}

opt_dynamic() {
    [ $_opt_dynamic -ne 0 ] && return 0
    return 1
}

opt_libseparate() {
    [ $_opt_libseparate -ne 0 ] && return 0
    return 1
}

opt_native() {
    [ $_opt_native -ne 0 ] && return 0
    return 1
}

opt_interop() {
    [ $_opt_interop -ne 0 ] && return 0
    return 1
}

opt_spfuncs() {
    [ $_opt_spfuncs -ne 0 ] && return 0
    return 1
}

get_options() {
    eval set -- "$(getopt -o atisNmwxldncvh -l ascii,reentrant,interop,spfuncs,native,msvcrt,woa,x86,libseparate,dynamic,nodebug,clean,verbose,help -- "$@")"

    while true
    do
	    case "$1" in
	        -a|--ascii)
	            _opt_widec=0
	            _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
	            shift
	            ;;
            -t|--reentrant)
	            _opt_reentrant=1
	            _cfgopts=$(expr $_cfgopts + 1)
	            _nondefault_opts=$(expr $_nondefault_opts + 1)
	            shift
	            ;;
            -i|--interop)
                _opt_interop=1
                _cfgopts=$(expr $_cfgopts + 1)
                shift
                ;;
            -s|--spfuncs)
                _opt_spfuncs=1
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -N|--native)
                _opt_native=1
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -l|--libseparate)
                _opt_libseparate=1
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -m|--msvcrt)
	            _opt_ucrt=0
	            _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
	            shift
	            ;;
            -n|--nodebug)
                _opt_debug=0
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -c|--clean)
                _opt_clean=1
                shift
                ;;
            -w|--woa)
                _opt_woa=1
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -x|--x86)
                _opt_x86=1
                _cfgopts=$(expr $_cfgopts + 1)
                _nondefault_opts=$(expr $_nondefault_opts + 1)
                shift
                ;;
            -v|--verbose)
                _opt_verbose=1
                shift
                ;;
            -d|--dynamic)
                _opt_dynamic=1
                _cfgopts=$(expr $_cfgopts + 1)
                shift
                ;;
            -h|--help)
                echo "Usage: $0 [options]"
                echo "Options:"
                echo "  -a, --ascii           Build ASCII version (disable wide character support)"
                echo "  -t, --reentrant       Build reentrant version"
                echo "  -i, --interop         Build with Windows interop features enabled. Only to be used with -N|--native"
                echo "  -s, --spfuncs         Build with sp-funcs support. Only to be used with -N|--native"
                echo "  -N, --native          Build for native execution in Linux (no cross-compilation)"
                echo "  -m, --msvcrt          Build with MSVCRT instead of UCRT"
                echo "  -w, --woa             Build for Windows on ARM (WOA) with UCRT"
                echo "  -x, --x86             Build for x86 (i686) with MSVCRT"
                echo "  -l, --libseparate     Build terminfo library separately from curses"
                echo "  -d, --dynamic         Build with shared libraries (default is static)"
                echo "  -n, --nodebug         Build without debug symbols and features"
                echo "  -c, --clean           Clean build and install directories before building"
                echo "  -v, --verbose         Enable verbose output"
                echo "  -h, --help            Show this help message and exit"
                shift
                exit 0
                ;;
	        --)
		        shift
		        break
		        ;;
	        *)
		        err="$err $1"
		        shift
		        break
		        ;;
	    esac
    done
}

consistency_checks() {
    if opt_spfuncs && ! opt_native; then
        _fail "sp-funcs support is only available for native builds."
    fi
    if opt_interop && ! opt_native; then
        _fail "Please specify interop only on native builds. On Windows it is implicit."
    fi
    if opt_native && ! opt_ucrt; then
        _fail "--msvcrt is a Windows specific option and cannot be used for native builds."
    fi
    if opt_native && (opt_x86 || opt_woa) ; then
        _fail "--x86 or --WoA are specific for Windows cross builds and cannot be used for native builds." 
    fi
    if opt_x86 && opt_woa; then
        _fail "x86 and WOA build options are mutually exclusive."
    fi
    if opt_x86 && opt_ucrt; then
        _fail "x86 builds for UCRT are not supported."
    fi
    if opt_woa && ! opt_ucrt; then
        _fail "WOA builds require UCRT."
    fi  
}

in_container || _fail "Not running in devcontainer." 

get_options $@
[ -n "$err" ] && _fail "Invalid options: $err"


_default_build=0
[ $_nondefault_opts -eq 0 ] && _default_build=1
if [ $_default_build -ne 0 ]; then
    _trace "Running with default settings (widec support, UCRT target, debug build)"
    _opt_widec=1
    _opt_ucrt=1
    _opt_debug=1
fi

consistency_checks

if ! opt_native ; then
# On Windows we enforce interop and disable spfuncs.
# This must be executed after consistency_checks
    _opt_interop=1
    _opt_spfuncs=0
fi

_relative_instroot=inst
_relative_buildroot=build

get_config_prefix() {
    local prefix=
    if opt_woa; then
        prefix="${CLANG64ARM_PREFIX}"
    elif opt_x86; then
        prefix="${MINGW32_PREFIX}"
    elif opt_native; then
        prefix=$NATIVE_PREFIX
    else
        if opt_ucrt ; then
            prefix="${UCRT64_PREFIX}"
        else
            prefix="${MINGW64_PREFIX}"
        fi
    fi
    echo "$prefix"
}

get_target_arch() {
    local arch=x86_64
    if opt_woa; then
        arch=aarch64
    elif opt_x86; then
        arch=i686
    elif opt_native; then
        arch=$(uname -m)
    fi
    echo "$arch"    
}

build_prefix() {
    local prefix=debug
    local arch=$(get_target_arch)
    local base=WindowsCross

    if ! opt_debug; then
        prefix=release
    fi
    echo "${prefix}/${base}/${arch}"
}

get_suffix() {
    local libsuffix=
    opt_reentrant && libsuffix="${libsuffix}t"
    opt_widec && libsuffix="${libsuffix}w"
    echo "$libsuffix"
}

get_extra_suffix() {
    local suffix=
    if opt_native; then
        opt_spfuncs && suffix="${suffix}s"
        opt_interop && suffix="${suffix}i"
    fi
    echo "$suffix"
}

relative_builddir() {
    local suffix=$(get_suffix)$(get_extra_suffix)
    local pre=$(build_prefix)
    local config_prefix=$(get_config_prefix)
    echo "${pre}/nc${suffix}/${config_prefix}"
}

relative_installbase() {
    local suffix=$(get_suffix)$(get_extra_suffix)
    local pre=$(build_prefix)
    echo "${pre}/nc${suffix}"
}

relative_installdir() {
    local config_prefix=$(get_config_prefix)
    echo "$(relative_installbase)/${config_prefix}"
}

_trace "Build prefix: $(build_prefix)"
_trace "Configuration prefix: $(get_config_prefix)"
_trace "Library suffix: $(get_suffix)"
_trace "Relative build directory: $(relative_builddir)"
_trace "Relative install base: $(relative_installbase)"
_trace "Relative install directory: $(relative_installdir)"

NCBUILD=${NC_WORKSPACE}/${_relative_buildroot}/$(relative_builddir)
if opt_clean; then
    _trace "Cleaning build directory: ${NCBUILD}"
    rm -rf "${NCBUILD}"
fi
_trace "NCBUILD: ${NCBUILD}, creating..."
mkdir -p "${NCBUILD}"

NCINST=${NC_WORKSPACE}/${_relative_instroot}/$(relative_installbase)
if opt_clean; then
    _trace "Cleaning install directory: ${NCINST}"
    rm -rf "${NCINST}"
fi
_trace "NCINST: ${NCINST}, creating..."
mkdir -p "${NCINST}"

build_bht=$(uname -m)-linux-gnu
host_bht=
if opt_woa; then
    host_bht="aarch64-w64-mingw32"
elif opt_x86; then  
    host_bht="i686-w64-mingw32"
else
    host_bht="x86_64-w64-mingw32"
    opt_ucrt && host_bht="x86_64-w64-mingw32ucrt"
fi
if ! opt_native; then
    env_file=$NC_WORKSPACE/.devcontainer/crossenvs/${host_bht}.env
    if [ -f "$env_file" ]; then
        _trace "Sourcing cross build environment from: ${env_file}"
        source "$env_file"
    else
        _fail "Cross build environment file not found: ${env_file}"
    fi  
    _trace "Host target compiler: ${host_bht}, Build environment: ${build_bht}"
fi

# When we are running in WSL2, we need to generate a .gdbinit file that contains 
# the correct paths to the repository and the WSL distribution name. This file 
# will be used by GDB to set up the environment for debugging Wincurses in Windows.
# This is necessary because we compile inside the container and gdb cannont generate
# source file references that are resolvable under Windows later on.
gen_gdbinit() {
    local d
    local p 
    pushd "$NC_WORKSPACE" >/dev/null
    for p in $(for d in ncurses panel menu form test; do find ncurses/$d -type d ; done | grep -v package)
    do
        echo "directory //wsl\$/${WSL_DISTRO_NAME}${ORIGINAL_REPO_PATH}/${p}"
    done
    echo "directory //wsl\$/${WSL_DISTRO_NAME}${ORIGINAL_REPO_PATH}/build/$(relative_builddir)/include"
    popd >/dev/null
}

# When we are running in Parallels Desktop, we need to generate a .gdbinit file that 
# contains the correct paths to the repository in the MacOS filesystem.  
gen_gdbinit_prl() {
    local d
    local p
    local win_p 
    source "${NC_WORKSPACE}/.prlpath" 
    pushd "$NC_WORKSPACE" >/dev/null
    win_p="${WIN_REPO_PATH//\\/\/}"
    for p in $(for d in ncurses panel menu form test; do find ncurses/$d -type d ; done | grep -v package)
    do
        echo "directory ${win_p}/$p"
    done
    p="build/$(relative_builddir)/include"
    echo "directory ${win_p}/$p"
    popd >/dev/null
}


do_config() {
    local srcdir=$NC_WORKSPACE/ncurses
    local cfg=$srcdir/configure
    local dynopts="--with-shared"
    local opts=
    local cflags= 
    local ldflags=
    local prefix=$(get_config_prefix)

    [ -x "$cfg" ] || _fail "Configure script not found or not executable: $cfg"

    if ! opt_native ; then
        opts="--build=${build_bht} \
            --host=${host_bht} 
            --with-strip-program=${STRIP} \
            --with-build-cc=${build_bht}-gcc \
            --with-build-cpp=${build_bht}-cpp"    
    fi

    if ! opt_dynamic; then
        dynopts="--without-shared"
    fi
    if opt_interop; then
        opts+=" --enable-interop"
    else
        opts+=" --disable-interop"
    fi
    if opt_spfuncs; then
        opts+=" --enable-sp-funcs"
    else
        opts+=" --disable-sp-funcs"
    fi
    if opt_reentrant; then
        opts="$opts --enable-reentrant"
    else
        opts="$opts --disable-reentrant"
    fi
    if opt_widec; then
        opts="$opts --enable-widec"
    else
        opts="$opts --disable-widec"
    fi

    if ! opt_native; then
        opts+=" --enable-named-pipes \
            --with-pcre2 \
            --disable-home-terminfo \
            --disable-symlinks \
            --with-fallbacks=ms-terminal \
            --without-manpages"
    fi    
    rm -rf "$NCBUILD"
    mkdir -p "$NCBUILD"
    _trace "Recreated build directory: ${NCBUILD}"

    if ! opt_native; then
        cflags="-I${PCRE2_ROOT}/include"
        ldflags="-L${PCRE2_ROOT}/lib -lpcre2-posix -lpcre2-8"
    fi

    opts="$opts --with-normal \
        --with-pkg-config \
        --without-cxx --without-ada \
        $dynopts"
    
    if opt_libseparate; then
        opts="$opts --with-termlib"
    else
        opts="$opts --without-termlib"
    fi

    if opt_debug; then
        cflags="$cflags -g"
        opts="$opts \
            --with-debug \
            --with-progs \
            --with-tests \
            --with-develop \
            --with-trace \
            --enable-asserts \
            --enable-database \
            --enable-db-install \
            --enable-warnings \
            --enable-assertions" 
    else
        opts="$opts \
            --without-debug \
            --without-progs \
            --without-tests \
            --without-develop \
            --without-trace \
            --disable-assertions \
            --enable-db-install"
    fi

    opts="$opts --disable-leaks \
        --disable-macros \
        --disable-getcap \
        --disable-hard-tabs \
        --disable-overwrite \
        --disable-termcap \
        --enable-opaque-curses \
        --enable-opaque-panel \
        --enable-opaque-menu \
        --enable-opaque-form \
        --enable-pc-files"

    if opt_dynamic; then
        if opt_native; then
            ldflags="-static-libgcc -Wl,-Bdynamic"
        else
            ldflags="-static-libgcc -Wl,-Bstatic -lwinpthread -Wl,-Bdynamic"
        fi
    fi

    _trace "Configuration options: ${opts}"

    pushd "$NCBUILD" >/dev/null
    CFLAGS="${cflags}" LDFLAGS="${ldflags}" \
    ${cfg} ${opts} --prefix="/${prefix}" \
        --datadir="/${prefix}/share" \
        --srcdir="${srcdir}"
    popd >/dev/null
    if ! opt_dynamic; then
        echo "S" > "$NCBUILD/.static"
        rm -f "$NCBUILD/.dynamic"
    else
        echo "D" > "$NCBUILD/.dynamic"
        rm -f "$NCBUILD/.static"
    fi
}

if [ ! -f "$NCBUILD/Makefile" ]; then
    do_config
else
    if ! opt_dynamic && [ -f "$NCBUILD/.dynamic" ]; then
        _trace "Configuration mismatch: previously configured for dynamic, now static. Reconfiguring..."
        do_config
    elif opt_dynamic && [ -f "$NCBUILD/.static" ]; then
        _trace "Configuration mismatch: previously configured for static, now dynamic. Reconfiguring..."
        do_config
    else
        _trace "Existing configuration matches current options. Skipping configuration step."
    fi
fi

make -j$(nproc) -C "$NCBUILD"
[ $? -ne 0 ] && _fail "Build failed"

if opt_debug && ! opt_woa ; then
    if maybe_parallels_desktop; then
        gen_gdbinit_prl > ${NCBUILD}/test/.gdbinit
        _trace "Generated .gdbinit for Parallels Desktop: ${NCBUILD}/test/.gdbinit"
    fi
    if in_wsl2; then
            gen_gdbinit > ${NCBUILD}/test/.gdbinit
            _trace "Generated .gdbinit for WSL2: ${NCBUILD}/test/.gdbinit"
    fi
fi

_trace "Installing to: ${NCINST}"
make -j$(nproc) -C "$NCBUILD" install DESTDIR="$NCINST"
[ $? -ne 0 ] && _fail "Install failed"
rm -rf "${NCINST}/opt"

exit 0
