#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/_inc

pushd $PROJROOT > /dev/null
_log "Cleaning build and install directories..."
rm -rf inst build
mkdir build
mkdir inst
popd > /dev/null

exit 0
