#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/internal/inc

pushd $PROJROOT > /dev/null
_log "Cleaning build and install directories..."
rm -rf inst build
mkdir build
mkdir inst
mkdir logs 2>/dev/null
popd > /dev/null

exit 0
