#!/usr/bin/env bash
# See License.md in the project root for license information.
#
SCRIPTS=$(cd $(dirname $BASH_SOURCE) && pwd)
. $SCRIPTS/_inc

stamp=$1
[ -n "$stamp" ] || _fail "No stamp passed as argument"

N=bba
M=current-${N}
R=job-${N}
L=logs
LN=${N}-${stamp}
LB=${L}/${LN}

tstart=$(date "+%s")

_sep() {
    echo "==================================================================================="
}

_elapsed() {
    local tend=$(date "+%s")
    local D=$(expr $tend - $tstart)
    echo $D
}

_timing() {
    echo "Duration: $1 Seconds"
}

_rename() {
    local ext="devc out err log job"
    local e
    local jobid
    [ -f "${LB}.job" ] || return 1
    source "${LB}.job"
    pushd $L >/dev/null
    for e in $ext
    do
        ln -f $LN.$e ${R}-\${jobid}.$e
        ln -f $LN.$e ${M}-\${jobid}.$e
        rm -f $LN.$e
    done
    popd >/dev/null
    return 0
}

_sep
echo "Running on $(uname -n), OS is $(uname -s)"
echo "Running at $(date)"
_sep
opts="--dynamic --libseparate"
cd $PROJROOT
./Scripts/ncnuke
echo "Bringig up devcontainer..."
devcontainer up --workspace-folder . --remove-existing-container >${LB}.devc 2>&1
if [ "$(uname -s)" = "Darwin" ]; then
    echo "Running buildall for Windows on ARM"
    devcontainer exec ncbuildall $opts --woa --log ${LB}.log 2>>${LB}.err >>${LB}.out
    D=$(_elapsed)
    _timing $D
    _timing $D >> ${LB}.log
    _sep >> ${LB}.log
fi

echo "Runnig buildall for Windows on Intel"
tstart=$(date "+%s")
devcontainer exec ncbuildall $opts --log ${LB}.log 2>>${LB}.err >>${LB}.out
D=$(_elapsed)
_timing $D
_timing $D >> ${LB}.log
cat ${LB}.log
_rename
exit 0
